---
name: Build
on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  go-build:
    uses: metal-stack/actions-common/.github/workflows/go-build.yaml@v1
    secrets: inherit
    with:
      build-command: make build
      test-command: make test

  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1
